---
title: "dplyr作业"
author: "王小二"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: pygments
    code_download: true
    code_folding: show
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---



# 作业

```{r}
library(tidyverse)
library(readxl)

d <- read_excel("./data/vowel_data.xlsx")
d 
```

# 问题

- 说出数据框中每一列的变量类型


- 构建新的一列FX，其中 $FX = F1^2 + F2^2$
```{r}
d %>% 
  mutate(FX = F1^2 + F2^2)
```

- 找出F1均值最大的元音

```{r}
d %>% 
  group_by(vowel) %>%
  summarise(
    mean = mean(F1)
  ) %>%
  filter(
    mean == max(mean)
  )

# or
d %>% 
  group_by(vowel) %>%
  summarise(
    mean = mean(F1)
  ) %>%
  arrange(-mean) %>%
  slice(1)  
```


- 找出F2波动最大的词语（提示，一般用标准差代表波动，`sd(F2)` ）

```{r}
d %>% 
  group_by(vowel) %>%
  summarise(
    sd = sd(F2)
  ) %>%
  arrange(-sd) %>%
  slice(1)  
```

- 计算F1 中心化值（提示：中心化 = 每个F1值 - 全部F1的均值， `F1 - mean(F1)`）
```{r}
d %>% 
  mutate(
    F1_c = F1 - mean(F1)
  ) 
```

- 按元音分组，计算 F1 中心化值
```{r}
d %>% 
 group_by(vowel) %>%
  mutate(
    F1_c = F1 - mean(F1)
  ) 
```

- 统计每个元音里，F1值高于该组均值的个数
```{r}
d %>% 
 group_by(vowel) %>%
 summarise(
    num = sum(F1 > mean(F1))
  ) 
```


