---
title: "案例学习"
subtitle: "元音舌位图"
author: "王小二"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: pygments
    code_download: true
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---




# 读取数据

```{r message = FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
d <- read_excel("./demo_data/vowel_data.xlsx")
d 
```

# 问题

- 以F2为横坐标和F1为纵坐标画出散点图，不同的元音用不同的颜色

```{r}
d %>%
  ggplot(aes(x = F2, y = F1, color = vowel)) +
  geom_point()
```


- 按元音分组，统计F1和F2的均值，然后画出F2和F1均值的散点图，不同的元音用不同的颜色

```{r}
m <- d %>%
  group_by(vowel) %>%
  summarise(
    mean_f1 = mean(F1),
    mean_f2 = mean(F2)
  )


m %>%
  ggplot(aes(x = mean_f2, y = mean_f1, color = vowel)) +
  geom_point(size = 5)
```



- 在上图每个点的位置加上元音标签

```{r}
m %>%
  ggplot(aes(x = mean_f2, y = mean_f1, color = vowel)) +
  geom_point() +
  geom_text(aes(label = vowel), size = 5)
```





- 思考把两张图画在一张图上

```{r}
d %>%
  ggplot(aes(x = F2, y = F1, color = vowel)) +
  geom_point() +
  geom_text(
    data = m,
    aes(x = mean_f2, y = mean_f1, label = vowel),
    size = 5
  )
```


- 给上图每个元音添加椭圆
(提示 `stat_ellipse(aes(fill = vowel), level = 0.8, geom = "polygon", alpha = 0.1)` )

```{r}
d %>%
  ggplot(aes(x = F2, y = F1, color = vowel)) +
  geom_point() +
  geom_label(
    data = m,
    aes(x = mean_f2, y = mean_f1, label = vowel),
    size = 5
  ) +
  
  stat_ellipse(aes(fill = vowel), level = 0.8, geom = "polygon", alpha = 0.1)
```





- 每个分面加灰色背景

```{r}
d %>%
  ggplot(aes(x = F2, y = F1, color = vowel, shape = vowel)) +
  geom_point() +
  facet_wrap(vars(vowel))
```



```{r}
d %>%
  ggplot(aes(x = F2, y = F1)) +
  geom_point(data = d %>% select(-vowel), 
             color = "gray") +
  geom_point(aes(color = vowel)) +
  facet_wrap(vars(vowel)) +
  theme(legend.position = "none")
```



- 横坐标反向且居上，纵坐标反向且居右

```{r}
d %>%
  ggplot(aes(x = F2, y = F1, color = vowel)) +
  geom_point() +
  
  scale_x_reverse(position = "top") +
  scale_y_reverse(position = "right") +
  labs(
    title = "这是我的元音舌位图",
    subtitle = "你觉得我这样美吗"
  ) +
  theme_classic() +
  theme(legend.position = "none")
```


- 在上图每个元音(F1/F2)的均值位置，添加元音的文本
```{r}
d %>%
  ggplot(aes(x = F2, y = F1, color = vowel)) +
  geom_point() +
  
  geom_label(
    data = m,
    aes(x = mean_f2, y = mean_f1, label = vowel),
    size = 5
  ) +
  
  scale_x_reverse(position = "top") +
  scale_y_reverse(position = "right") +
  labs(
    title = "这是我的元音舌位图",
    subtitle = "你觉得我这样美吗"
  ) +
  theme_classic() +
  theme(legend.position = "none")
```


- 在上图的基础上，每个元音添加自己的椭圆
```{r}
d %>%
  ggplot(aes(x = F2, y = F1, color = vowel)) +
  geom_point() +
  
  stat_ellipse(level = 0.8, geom = "polygon", alpha = 0.1, aes(fill = vowel)) +
  
  geom_label(
    data = m,
    aes(x = mean_f2, y = mean_f1, label = vowel),
    size = 5
  ) +
  scale_x_reverse(position = "top") +
  scale_y_reverse(position = "right") +
  labs(
    title = "这是我的元音舌位图",
    subtitle = "你觉得我这样美吗"
  ) +
  theme_classic() +
  theme(legend.position = "none")
```







- 在上图的基础上，坐标轴标签添加单位HZ

```{r}
library(scales)
d %>%
  ggplot(aes(x = F2, y = F1, color = vowel, shape = vowel)) +
  geom_point() +
  stat_ellipse(level = 0.8, geom = "polygon", alpha = 0.1, aes(fill = vowel)) +
  geom_label(
    data = m,
    aes(x = mean_f2, y = mean_f1, label = vowel),
    size = 5
  ) +
  
 scale_y_reverse(
   position = "right",
   labels = unit_format(unit = "Hz", sep = ""),
   breaks = seq(100, 1000, 200)
 ) +
 scale_x_reverse(
   position = "top",
   labels = unit_format(unit = "Hz", sep = ""),
   breaks = seq(200, 3000, 500)
 ) +
  
  labs(
    title = "这是我的元音舌位图",
    subtitle = "你觉得我这样美吗"
  ) +
  theme_light() +
  theme(
    legend.position    = "none",
    plot.title         = element_text(hjust = 0.5), 
    plot.subtitle      = element_text(hjust = 0.5),
    text               = element_text(size = 13),
    plot.margin        = margin(t = 1, r = 0.8, b = 1, l = 1, "cm"),
    axis.title.y.right = element_text(angle = 0, vjust = 0.5)
  )
```




- 把"a", "i", "u" 三个元音的中心点，连起来构成三角形

```{r}
m %>% 
  filter(vowel %in% c("a", "i", "u")) %>%

  ggplot(aes(x = mean_f2, y = mean_f1)) +
  geom_polygon(color = "black", fill = "white") +
  geom_point(size = 3, color = "red") +
  geom_point(size = 30, shape = 1) +
  scale_x_continuous(
    expand = expansion(mult = 0.2)
  ) +
  scale_y_continuous(
    expand = expansion(mult = 0.2)
  ) +
  theme_classic() 
```

