---
title: "dplyr across"
subtitle: "企鹅的故事"
author: "王小二"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: pygments
    code_download: true
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---



# 导入数据

```{r message = FALSE, warning = FALSE}
library(tidyverse)

penguins <- read_csv("./demo_data/penguins.csv") 
penguins
```


# across()之美

我们想知道，嘴巴长度和嘴巴厚度的均值

```{r}
penguins %>%
  summarize(
    length = mean(bill_length_mm)
  )
```

接着添加下个变量
```{r}
penguins %>%
  summarize(
    length = mean(bill_length_mm),
    depth  = mean(bill_length_mm)
  )
```

长度和厚度惊人的相等。我是不是发现新大陆了？



更安全、更简练的写法，王老师的最爱

```{r}
penguins %>%
  summarize(
     across(c(bill_depth_mm, bill_length_mm), mean)
 )
```

翅膀的长度加进去看看

```{r}
penguins %>%
  summarize(
     across(c(bill_depth_mm, bill_length_mm, flipper_length_mm), mean)
 )
```


还可以更简练喔
```{r}
penguins %>%
  summarize(
     across(ends_with("_mm"), mean)
 )
```


`across()`函数用法

```{r, eval = FALSE}
across(.cols = everything(), .fns = NULL, ..., .names = NULL)
```

- 用在 `mutate()` 和`summarise()` 函数里面
- `across()` 对**多列**执行**相同**的函数操作，返回**数据框**




## 数据中心化

```{r}
penguins %>%
  mutate(
    bill_length_mm = bill_length_mm - mean(bill_length_mm),
    bill_depth_mm  = bill_depth_mm  - mean(bill_depth_mm)
    )
```


更清晰的办法

```{r}
centralized <- function(x) {
  x - mean(x)
}


penguins %>%
  mutate(
    across(c(bill_length_mm, bill_depth_mm), centralized)
  )
```

或者
```{r}
penguins %>%
  mutate(
    across(c(bill_length_mm, bill_depth_mm), function(x) x - mean(x))
  )
```

或者
```{r}
# using purrr style
penguins %>%
  mutate(
    across(c(bill_length_mm, bill_depth_mm), ~ .x - mean(.x))
  )
```



::: {.rmdnote}

```{r, eval=FALSE}
function(x)  x^2 + 5

~ .x^2 + 5
```

这是两种等价的写法。


这里的 `.x` 又可以写成 `.`  

```{r, eval=FALSE}
~ .^2 + 5
```

最后一种是偷懒到极致的写法

:::



## 数据标准化

```{r}
std <- function(x) {
  (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)
}


penguins %>%
  mutate(
    across(c(bill_length_mm, bill_depth_mm), std)
  )
```


或者
```{r}
penguins %>%
  summarise(
    across(starts_with("bill_"), ~ (.x - mean(.x)) / sd(.x))
  )
```



## 对多列执行多个统计函数

```{r}
penguins %>%
  group_by(species) %>%
  summarise(
    across(ends_with("_mm"), list(mean, sd))
  )
```


最好给每个函数取个名字
```{r}
penguins %>%
  group_by(species) %>%
  summarise(
    across(ends_with("_mm"), list(mymean = mean, mysd = sd))
  )
```



**随堂练习**：
- 以sex分组，对"bill_"开头的列，求出每列的最大值和最小值


```{r}
penguins %>%
  group_by(sex) %>%
  summarise(
    across(starts_with("bill_"), list(max = max, min = min), na.rm = TRUE)
  )
```



